version: '3.8'

services:
  cognito:
    image: jagregory/cognito-local
    container_name: cognito-local
    ports:
      - "9229:9229"
    environment:
      AWS_REGION: "us-east-1"
      AWS_COGNITO_ENDPOINT: "http://localhost:9229"
      AWS_COGNITO_USER_POOL_ID: "local_27fobjwC"
      AWS_COGNITO_CLIENT_ID: "edhmf49c9f8zlcbgdkxe4o6mn"
    restart: always

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "admin123"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  minio_data:
